name: Simple Mock Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.calculate_version.outputs.version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Calculate version
      id: calculate_version
      run: |
        version="1.2.3"
        echo "version=$version" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use version from job1
      run: |
        echo "The version from job1 is ${{ needs.job1.outputs.output1 }}"
